apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage-class-luks.yaml
  - postgres-ha.yaml
  - postgres-init-pgvector.yaml
  - hapi-fhir.yaml
  - redis-cluster.yaml
  - minio.yaml
  - network-policies.yaml
  - cert-manager-issuer.yaml
  - external-secrets.yaml
  - nats-jetstream.yaml
  - airflow.yaml
  - mlflow.yaml
  - torchserve-ctg.yaml
  - monitoring.yaml
  - evidently-drift-job.yaml
commonLabels:
  app.kubernetes.io/part-of: obstetric-ai
